<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>c861ca3f-76b2-4596-aa9f-8182051422a6</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Controllers\TestController.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ControleOrdemDeServico.ServiceDefaults\OsService.ServiceDefaults.csproj" />
		<ProjectReference Include="..\ControleOrdemDeServico.Services\OsService.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="14.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
	</ItemGroup>

</Project>